### ISSUE TITLE
Create separate issues for testing each dance

### ISSUE THREAD

**Issue by romainfrancois** [romainfrancois/dance#5]
Each `dance()` function needs to be tested. Create separate issues for each and perhaps comment here that you've done it. 

This way, these issues are small goals that can be tackled separately.

**Comment by dragosmg** [comment]
@romainfrancois I'm happy to create issues for testing each dance. 
Should we include a suggestion to use `usethis::use_test("dance")` in order to create the test file? 
Any recommended approaches - one test file per function or one test file per source file?

**Comment by dragosmg** [comment]
I went on with `usethis::use_test("function")` approach and one test file per function. Issues created for:
- [ ] test `waltz()` - issue #29 
- [ ] test `polka()` - issue #30
- [ ] test `charleston()` - issue #31
- [ ] test `tango()` - issue #32
- [ ] test `swing()` - issue #33
- [ ] test `twist()` - issue #34
- [ ] test `rumba()` - issue #35
- [ ] test `zumba()` - issue #36
- [ ] test `salsa()` - issue #37
- [ ] test `chacha()` - issue #38
- [ ] test `samba()` - issue #39
- [ ] test `madison()` - issue #40
- [ ] test `bolero()` - issue #41
- [ ] test `mambo()` - issue #42

That should cover all functions currently in `README.Rmd`

**Comment by romainfrancois** [comment]
Thanks that’s great. Sorry I missed the previous comment.

**Comment by dragosmg** [comment]
Cool, no worries. I hope the approach I've taken is ok.

**Comment by romainfrancois** [comment]
Yeah it's alright. closing this issue now.
